### ISSUE TITLE
Update and clean up documentation

### ISSUE THREAD

**Issue by Tapawingo** [Tapawingo/TAKlib#6]
## Introduction
The current documentation located at: [./wiki](https://github.com/Tapawingo/TAKlib/wiki) is too sparse and doesn't go in depth enough. It is also out of date with the current version of TAKlib and thus is missing the new functions.
### Goals:
- [ ] Go more in depth on each of the function notations and provide more info on exception handling, data handling and expected data types
- [ ] Update doumentation to align with the current TAKlib version

**Comment by brothercorvo** [comment]
@naman108 please clean this up, modifying the main MD file so that we can close it

**Comment by brothercorvo** [comment]
closed in 0.5 will open a new more specific one
