### ISSUE TITLE
Produce proper HTTP replies

### ISSUE THREAD

**Issue by Tapawingo** [Tapawingo/TAKlib#7]
## Introduction
TAK devices creates an asynchronous connection on port 8080 where they send various http requests.
Upon opening a connection on the main socket it will send 2 HTTP/1.1 GET requests, one for the server version and one for the server config. It may also later be used for sharing mission packages.

### Goals:
- [ ] Re-write current HTTP handler to produce proper responses and provide the materials requested.
- [ ] Allow for storing and distribution of mission packages

**Comment by brothercorvo** [comment]
Adressed in 0.3
