### ISSUE TITLE
Validate incoming data before broadcast and general security issues

### ISSUE THREAD

**Issue by Tapawingo** [Tapawingo/TAKlib#8]
Re-write the current connection handler to properly validate data before broadcasting it to other clients. 
### Goals:
- [x] Parse XML and validate it's integrity.
- [x] Grab user UID from initial thumbprint and require for all received packages as either a direct UID match or a linked UID match
- [ ] Allow proper handling for TLS/SSL connections

**Comment by reldred** [comment]
With platform; remember that there's also WinTak and a fabled iPhone version (that I have but have never gotten working) that won't pass the existing platform check. Using the example server in your 0.3 branch I had to force that check to return True and the UID in both instances. Was able to connect to the server, and the logs showed that on events such as creating/deleting objects that it was receiving data but WinTak clients timed out frequently and never seemed to receive data/objects. Couldn't get the example server in Master to work; logs kept indicating it was trying to write to an xml file in '/home/natha/'.

Sorry that's a bit long and rambling, I spent 0200-0400 screwing around with it and that's my incoherent thoughts 👍

**Comment by brothercorvo** [comment]
We are trying a variety of approaches but until now we were not successful in transmitting properly to all the clients. The last version can get messages but not broadcast them

**Comment by reldred** [comment]
Nice. I've had a chance recently to get some exposure to TAKServer and it's a bit of a dogs breakfast. You folks have got the opportunity to make something a hell of a lot more streamlined and usable.

**Comment by brothercorvo** [comment]
We plan to address authentication in version 0.5

**Comment by brothercorvo** [comment]
Connecting to a TAK Server has two 'certificates' in the form of X.509 files.

keystore-name.p12

truststore-name.p12

One will be to identify the user, the other to connect to the server port and/or federate, and to authenticate to services like the "FTP-like" service for files access on the TAK Server such as Mission Packages. Called Client Certificates and Server Certificates.

**Comment by brothercorvo** [comment]
close it to reopen it as "Allow proper handling for TLS/SSL connections"
