### ISSUE TITLE
TAK devices fails to synchronize over WAN-like networks

### ISSUE THREAD

**Issue by Tapawingo** [Tapawingo/TAKlib#9]
When trying to sync a local device with a remote device it fails. As of now it's unknown what's causing this.
### Currently tested:
4G                                -->                                       4G fails
Local (behind firewall) -->                                        4G fails
Local (behind firewall) <--                                        4G fails
Local (behind firewall) --> Local (behind firewall)    succeeds

**Comment by Tapawingo** [comment]
It seems that the server isn't broadcasting properly and that the clients will automatically broadcast on any local network it's connected to hence why i got a false positive when testing before.

**Comment by brothercorvo** [comment]
we were able to send a Cot to the connected devices but the format is not  accepted
<?xml version="1.0" standalone="yes"?>
<event
version="2.0"
uid="J-01334"
type="a-.-G-E-W-O"
time="2020-02-08T01:27:58Z"
start="2020-02-08T01:27:58Z"
stale="2020-02-08T01:28:58Z"
how="m-i">
	<detail></detail>
	<point
		lat="30.0090027"
		lon="-85.9578735"
		hae="-42.6"
		ce="45.3"
		le="99.5"/>
</event>} -- Unable to parse XML

**Comment by Tapawingo** [comment]
This issue has been resolved as of version 0.3a
